---
# tasks file for iptables

  - name: install iptables
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - iptables
      - iptables-persistent

  - name: enable ipv4 forwarding permanently
    lineinfile:
      path: "{{ sysctl_conf_location }}"
      regexp: '#net.ipv4.ip_forward=1'
      line: 'net.ipv4.ip_forward=1'
      state: present
      create: false
    notify: restart_pi
    tags: iptables

  - name: accept loopback interface input
    iptables:
      chain: INPUT
      in_interface: "{{ item }}"
      jump: ACCEPT
    with_items:
      - eth0

  - name: input accept chain
    iptables:
      chain: INPUT
      jump: ACCEPT
      ctstate: ESTABLISHED,RELATED
      match:
        - state

  - name: wlan0 postrouting nat
    iptables:
      jump: MASQUERADE
      out_interface: wlan0
      chain: POSTROUTING
      table: nat

  - name: eth0 to wlan0 forward rule
    iptables:
      jump: ACCEPT
      ctstate: ESTABLISHED,RELATED 
      match:
        - state
      chain: FORWARD
      out_interface: eth0
      in_interface: wlan0

  - name: wlan0 to eth0 accept rule
    iptables:
      jump: ACCEPT
      chain: FORWARD
      out_interface: eth0
      in_interface: wlan0
  
  - name: Save iptables to file
    shell: iptables-save > /etc/iptables/rules.v4