---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    iptables_persistent_location: '/etc/iptables/rules.v4'

  tasks:
  - name: Save iptables file location to variable
    stat:
      path: "{{ iptables_persistent_location }}"
    register: stat_result

  - name: Check if iptables file exists
    assert:
      that: stat_result.stat.exists

  - name: check content of iptables file
    copy:
      src: './molecule/files/rules.v4.compare'
      dest: "{{ iptables_persistent_location }}"
    check_mode: yes
    register: result
    failed_when: result.changed